import { describe, it, expect, vi, beforeEach } from "vitest";
import { runInboundAiPipeline } from "./inboundAiPipeline";
import { sendConversationReply } from "./outboundReply";
import { studentWhisper } from "@workspace/ai-student";
import { retrieveClassroomFacts } from "./knowledge";
import { db } from "./db"; 

// ============================================================================
// HOISTED VITEST MOCKS (The Seams)
// ============================================================================
vi.mock("./outboundReply", () => ({
  sendConversationReply: vi.fn(),
}));

vi.mock("@workspace/ai-student", () => ({
  studentWhisper: vi.fn(),
}));

vi.mock("./knowledge", () => ({
  retrieveClassroomFacts: vi.fn(),
}));

describe("Texitie Auto-Pilot Regression: Outbound Send Interruption Fault-Tolerance", () => {
  const mockTenantId = "tenant_test_9999_throwaway";
  const mockInboundSid = "inbound_sid_test_12345";
  const mockConvoId = "convo_id_test_abcde";

  beforeEach(() => {
    vi.clearAllMocks();
  });

  // ============================================================================
  // TEST CASE 1: FORCED THROWN SEND (TERMINAL BLUE HANDBACK)
  // ============================================================================
  it("should release claim lock and set AI state to failed without re-throwing if Twilio explodes", async () => {
    vi.mocked(sendConversationReply).mockRejectedValue(new Error("twilio exploded"));
    
    vi.mocked(studentWhisper).mockResolvedValue({
      confidenceScore: 0.98, 
      draftMessage: "This is a clean autopilot response generated by the Professor.",
      category: "safe_customer_faq"
    });

    vi.mocked(retrieveClassroomFacts).mockResolvedValue([
      { id: "fact_1", content: "Texitie runs on autonomous autopilot text logic." }
    ]);

    await db.query("INSERT INTO tenants (id, engagementMode) VALUES (?, 'autopilot') ON DUPLICATE KEY UPDATE engagementMode='autopilot'", [mockTenantId]);
    await db.query("INSERT INTO conversations (id, tenant_id, status) VALUES (?, ?, 'active')", [mockConvoId, mockTenantId]);
    
    const initialKnowledgeCount = await db.query("SELECT COUNT(*) as count FROM classroom_facts WHERE tenant_id=?", [mockTenantId]);

    const inboundPayload = { sid: mockInboundSid, conversationId: mockConvoId, body: "Hello Texitie" };
    
    await expect(
      runInboundAiPipeline(mockTenantId, inboundPayload)
    ).resolves.not.toThrow(); 

    const activeClaims = await db.query("SELECT * FROM ai_auto_replies WHERE tenant_id=? AND inbound_sid=?", [mockTenantId, mockInboundSid]);
    expect(activeClaims.length).toBe(0);

    const aiState = await db.query("SELECT * FROM conversation_ai_states WHERE conversation_id=?", [mockConvoId]);
    expect(aiState.status).toBe("failed");
    expect(aiState.reason).toBe("send_failed");

    const postKnowledgeCount = await db.query("SELECT COUNT(*) as count FROM classroom_facts WHERE tenant_id=?", [mockTenantId]);
    expect(postKnowledgeCount.count).toBe(initialKnowledgeCount.count);
  });

  // ============================================================================
  // TEST CASE 2: PRE-SEND FAILURE (COMPLEMENTARY RE-THROW RULE)
  // ============================================================================
  it("should aggressively propagate and re-throw errors if a pipeline system failure occurs BEFORE the send event", async () => {
    vi.mocked(studentWhisper).mockRejectedValue(new Error("Database connection timed out internally"));

    const inboundPayload = { sid: mockInboundSid, conversationId: mockConvoId, body: "Hello Texitie" };

    await expect(
      runInboundAiPipeline(mockTenantId, inboundPayload)
    ).rejects.toThrow("Database connection timed out internally");
  });
});
