import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import tenantAuthRouter from "./tenantAuth";
import tiersRouter from "./tiers";
import tenantsRouter from "./tenants";
import injectionsRouter from "./injections";
import webhooksRouter from "./webhooks";
import statsRouter from "./stats";
import complianceRouter from "./compliance";
import conversationsRouter from "./conversations";
import departmentsRouter from "./departments";
import phoneNumbersRouter from "./phoneNumbers";
import phoneProvisioningRouter from "./phoneProvisioning";
import telephonyRouter from "./telephony";
import agentsRouter from "./agents";
import billingRouter from "./billing";
import automationsRouter from "./automations";
import shortcutsRouter from "./shortcuts";
import campaignsRouter from "./campaigns";
import analyticsRouter from "./analytics";
import dispositionsRouter from "./dispositions";
import contactsRouter from "./contacts";
import remindersRouter from "./reminders";
import auditLogsRouter from "./auditLogs";
import optInsRouter from "./optIns";
import integrationsRouter from "./integrations";
import tenantSettingsRouter from "./tenantSettings";
import surveysRouter from "./surveys";
import surveysPublicRouter from "./surveysPublic";
import eventsRouter from "./events";
import knowledgeRouter from "./knowledge";
import brainRouter from "./brain";
import migrationsRouter from "./migrations";
import csvImportsRouter from "./csvImports";
import brandSafetyRouter from "./brandSafety";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(tenantAuthRouter);
router.use(tiersRouter);
router.use(tenantsRouter);
router.use(injectionsRouter);
router.use(webhooksRouter);
router.use(statsRouter);
router.use(complianceRouter);
router.use(conversationsRouter);
router.use(departmentsRouter);
router.use(phoneNumbersRouter);
router.use(phoneProvisioningRouter);
router.use(telephonyRouter);
router.use(agentsRouter);
router.use(billingRouter);
router.use(automationsRouter);
router.use(shortcutsRouter);
router.use(campaignsRouter);
router.use(analyticsRouter);
router.use(dispositionsRouter);
router.use(contactsRouter);
router.use(remindersRouter);
router.use(auditLogsRouter);
router.use(optInsRouter);
router.use(integrationsRouter);
router.use(tenantSettingsRouter);
router.use(surveysRouter);
router.use(surveysPublicRouter);
router.use(eventsRouter);
router.use(knowledgeRouter);
router.use(brainRouter);
router.use(migrationsRouter);
router.use(csvImportsRouter);
router.use(brandSafetyRouter);

export default router;
